SELECT EMPLOYEE_ID AS ID, FIRST_NAME as FN, LAST_NAME AS LN
FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%r%';

SELECT EMPLOYEE_ID AS ID, FIRST_NAME as FN, LAST_NAME AS LN
FROM EMPLOYEES 
WHERE FIRST_NAME LIKE '%xa%'; 