rem 2) Find out if there are any employees without a manager.

--SELECT * FROM employees;

--SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES;

--SELECT EMPLOYEE_ID AS ID, FIRST_NAME as FN, LAST_NAME AS LN, MANAGER_ID AS MID FROM EMPLOYEES WHERE MANAGER_ID=124;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;