rem 6) Find out what employees are in the department 10 and 100.

--SELECT * FROM employees;


SELECT EMPLOYEE_ID AS ID, FIRST_NAME as FIRST_N, LAST_NAME AS LAST_N, DEPARTMENT_ID AS DEP_ID
FROM EMPLOYEES 
WHERE DEPARTMENT_ID=10
OR DEPARTMENT_ID=100;